name: Screenshots

on:
  workflow_dispatch:

jobs:
  e2e:
    name: 🎭 Re-Generate Test Screenshots
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v${{ vars.PLAYWRIGHT_VERSION }}
    strategy:
      fail-fast: false
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.13.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v7

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 🗑️ Delete existing screenshots
        run: find . -name "*-linux.png" -type f -delete

      - name: 👩‍🔬 Regenerate test screenshots 🎭
        run: HOME=/root npx playwright test --update-snapshots

      - name: 🆙 Upload test screenshots
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-screenshots
          path: src/components/**/*.png
          retention-days: 30
