on:
  workflow_call:

jobs:
  typecheck:
    name: ʦ TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.13.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 🔎 Type check
        run: npm run typecheck

  lint_code:
    name: ⬣ ESLint
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.13.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 🔬 Lint code
        run: npm run lint:code

  lint_styles:
    name: ⬣ Stylelint
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.13.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 🔬 Lint styles
        run: npm run lint:styles

  lint_slowtypes:
    name: 🦕 Slow Types
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.13.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 🔎 Type check
        run: npm run lint:slowtypes

  build_components:
    name: 🏗 Build Web Components
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.13.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 🏗 Build web components
        run: npm run build:components

      - name: ♻️ Upload to dist folder
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: dist
          path: ./dist

  build_storybook:
    name: 🏗 Build Storybook
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.13.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 🏗 Build Storybook
        run: npm run build:storybook

      - name: ♻️ Upload static folder
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: storybook-static
          path: ./storybook-static

  e2e:
    name: 🎭 Test
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v${{ vars.PLAYWRIGHT_VERSION }}
    strategy:
      fail-fast: false
      matrix:
        project: [chromium, firefox, webkit, 'Mobile Chrome', 'Mobile Safari']
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.13.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 👩‍🔬 Test with Playwright 🎭
        run: HOME=/root npx playwright test --project="${{ matrix.project }}"

      - name: 📺 Show coverage 🎭
        run: HOME=/root npm run coverage:report:text

      - name: 🙈 Check full test coverage 🎭
        run: HOME=/root npm run coverage:check

      - name: 🆙 Upload test results
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: test-results
          path: ./test-results-${{ matrix.project }}
          retention-days: 30
